---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cost-tracker
  namespace: cost-tracker
spec:
  encryptedData:
    DATABASE_URL: |-
      AgA9ZX+mBpA0aUCpmebsgr4ycE2MmBdFUEagLyBQ9tKlR4MVOJtzTFLYW+Ot8MOOOrXup9iIZj
      r2hgARdRKuB2U/EoK7Bv7Z8BmluHQjivecV0jy1VXjwPYP7Wrc74twqE/bt7uHq5mjqYliBnbM
      EX9+WI16Ks2rvMHbWoIU6vKxjLSqdJPbgkXkBUTO5CHBNS2Ds4eu0+D155w0AmphAcdXjIEbxf
      W8xwMcv8nZBBXBVKvv2Lz3oDiScgvZyJmamS9aKjOMGL0Uxcvx12iidxOVv5kxudDanSg7d6LP
      PmgFaRinQH44nZ5LungTMjqblXfzgQvxPusWY20vUmalov2nJRUImFTPaeFtBcrs1dDyXYk0zV
      GGutlPKQTn4nz+VARQkLOybT7yZMMEJbu5G/2q5bk+Eh9ncJjeMP+AFf7RFllmdJ3wGVTdLlaR
      Qd2xIQx2fdChWycS4RPEIIP+UymY94G2BiOLUVdb1Wo4FjNV4q/e7jf7ps4CEZ9IG1zeNMIY+J
      sTzpVeyHUH0ESvWjxlagbx/vTC+KNyID6tABcT6bUKwIS4a6M3DhcstZ4tw4RutWLSKWgMbQTG
      JWkyIFmjw/Jl9PssS8KOdcNGr2QcK4xUsNHt97smrX/PJt8X96lanaD/AucFN3dwyzBGy20OsA
      Lkvwl+//dpvFPvVa6psAiw49meuzgcYzJ9VpZ2fxcHCczQSfH3uyLEUp9RuL1RyLaL2xg5IaXi
      VDFJQmgfjm/1NaoErGmu/AjSg4bldfwXvpWSWGAHWQc4h+047LJi5c+vlyA1HATmul+dQ5BncF
      vClCtuMsds3hWu6YD+r+G57CuudeCk/4w6528GH8yvoj1deJIerQLJGK84UD7lN44=
    GLANCE_API_KEY: |-
      AgAEn+c9Q+4ssdb1TvAc2c+FAMkFYcVfaDk8qgyYfSSPx9eA81Luj/IfTG7h6tUdg6vUiWEdPR
      l2h0LxPc4cnx4jNA5bBA8jizx/sGTDvzsuiIumerIsJMx8qSj7m4ZcJy7J9lXHo1+AFnpJ6FFp
      HVenOarJCiCMMCr1UvjSJpu+FkYclMSVT0YSSCaPr7qsPBtW7GRTBXzKU6Uttzlv04v9R1Njxb
      8OnYUIxKOuIplNmQPk+i+EV24V1kd2e0KQRHP1uJim3fIeqQuSlmTeh72iRlrrLPq1vcubt/F9
      PXNiQy4QTdFXb7/tNpUNNUvP37XbLl+OwYyZJ+goMl8lMmKeTgjDDL0ib63hcoFhFUxl1JdQnD
      tOongzxIUayqvyWqioRndYib6+92Dex4iYc1Yrfnctp7SNXYDAWNfCctZtPUKThZ8HofYhmqSB
      LJsBMouH/VqAUbYZQjO5O2scf+gSKlbXGt/uTgL/lbhemwEer076BSSKSfXYgNe2H5w+JpRULN
      lmdn/+WCHzLDE62yoVw+2byST/W1CqJYd2LimDXLTJcDV6Qe8ViK4o+fHJoIR7PTYGWtHiXgnh
      2P9Sk3R2wQ5Jh5TxCU0vpDh+Y8WNmcLDEwA12lAX+FV7PJrS1OipJCDCKwLkG9IJc47YPGVIgP
      fm2Rp4ABTIqWKa5gsRqckBZkGTBH/7UYM624nbjKFhxtA5s3G8WlTfXpbo/TmU6NubX/541sw=
    INTERNAL_WEBHOOK_SECRET: |-
      AgAYiQ6vGBv5aJReKvMajYjN83yurQFkUZ5LNYooLILGVCMDSeF4wP1NdeIRzHH4krLdZJ/YfO
      eevV2AqYMh8EnGDP+L26dJE3DWAbGOR69hauutqbQWcEU/tzQcx2IN2s3WDzL0sip4De9RdTZJ
      D/g0mMX9BXXMmRQHS0UAxXfziAh4w6vhQxDyergWH301adJnJp8q04Vh5zv8DDIdy7kUC2HOl8
      BfuV0xUW4qfpt2CI41/mU3GHtZBvL9uOkheIq1V4s+uLwOrnV2frtFxyQJED0PJNqHGh3PpH6r
      eUgtW1GVu0N3qtin07sEFPWusUE0/GJvir/sc5yyKQeNjAAx4hWyYpuDiEWtRKwPyOQqqpPpBA
      SVMlkS1KnIdp1AwDSoW7pXLxyk1/YCygCLgX2hM7nl9otaI6dsGdijuAneWI0YHRuaiieYY3t6
      HwwZk/ij1vriE20Tyl3kMygUwg3wq7gqyflsW0/uM2RB9riVk4m98x6jaCjPQMNtq/tDSvfZ9j
      A8F1OUrP2sJdXnlpCrRbh4JNJTru0+T5LDGsvJ47Cv5s5JD8/ohKAq2HizCRvAEh4IvhSbNixt
      fbm9RMcl+UepCeIdF1JOKpHWi1JkF8UHhOc4UrbDzNFU6IXEHcUuL/q1Doci+C14t9TU95Qwhh
      dDh8lgOFoKbMGwNWxwTfUH8zXvTHgVD3CVSdbwccsVMBhHmSsSriqCyiPerbOP3lBz9/GY3B4=
    OIDC_CLIENT_ID: |-
      AgCZH0xkf7IPMH4dp0ZF6Mm5je48yLRaWseC091akYuZbsnaEqt2kz6Dkj6niT7X76g7EBa4Y5
      dNr1AkZivR3vS/uK/C2zlMmtZ0aTFu/VSVxFD9MY5m1zVO2PfMCPJxh21yC1t8JkK2Mzb0Ln0n
      3aTfg0MaA3k45e5MtnkTzcEAiS993yYsdWyYH7DMYEI8Hp6J36UgCg8yZNHQYfowvrvP8EJYuU
      LqsGE5A7umUuOyuKx5ELUZsrvRmVLtwH0Nah7ZW5s2HGdLqOpFhmN66sr7UvApkGrNg/xMNdLy
      7eq7z7Oy8nuWZAXTNz4oauXoNqoVIIcALziWwhM7Rp8Su9KJQex6zLlon3dQHF2SY/2AnAsk24
      G+uDKN9zUWfucb1YqIZ4A5GHa1rI4upSe3Z9AAv05bgv9RiNAkcgpnkhq4yycgOtb0KADoqdKO
      I9LZonbSPtv+DyIA8vJJW6ZV9rGJ17Oq0QngOIR2/QjGDcCLmiCE5jz6RHNxHsSCjum1tYVO86
      kt9y+mAjs7/X/XmLfPFEG7D9vyTljgLc33EvFJDIxviIEPP0lmBv/WvxtBE6nhE9L/ub2lmQNW
      wVoe74WLqLFmh1JAdYYlH5SL9IE9wC/xYeOIREovQlJv5L4XazxNW7p4pzzdhk4QFak9olBw75
      RIO3UlSn4qAxOuNJA8KyB5lCY17GaMkEjibmLzvQQF+28RpWev0Rsp3cknMonBvrD48/Dh8CLO
      yqxLalthyoUUnq/anBZo
    OIDC_CLIENT_SECRET: |-
      AgA5XdHmTBquQTF/1rBiIYH0Y8Ilu2G0UfWSv4GDTS4m94ZPM0W46owyGibHPUH5HwA5UXgdeo
      TPKDwTvL9g/oYCcpO/jbJhzIhkvgktzjnq5gtqG4YHF3O8QD3PH+AIYWaELVZ5eeusxHe257Vx
      kafiRB32yZ1H+nWE1YaQes6KknPkAjIaXKlw8TvJ7KFbF3PcJL60hHYDYv3AflBWnCR7/fCQdJ
      bHRyk3K6iF+0mCRCSKTni1vTtG73HO29tD5GwZssNUA89fzn+UW+3v8EuHLgMxGLyufGKihi1M
      3Kc8afY6CKH8lZeFS4t5DYoRFyc6uHAxakgPZT6QnYi+/XbRry1Y1utAhKS+0QGrbn5bPPv3bX
      qOfDSzh84KHBQdo2D8LfxVrV/Ls1/MxYXzpDfSElB/w/VinOf4j5wlAKiLrC/Ufv+w3G5uUxZ5
      mgDYMUTlG9Fym4szW7ot8Vl3uUI4ItoiLdU3uRsQUPP1xW2y5ngoc7aeQqCz+mX0iXSFgkzMHk
      Tidfu6X7CGl9RBdbP/kHwZGgWjGZNxeJ8bs4pSUOD7yq8clHXLBGob26DvKhZhf0URtSmJv+I2
      7JahvaKlvIAhZQZI23aIH6H9IasbIqy4qkEAFez0K9s215IaTIbBOXzWdWNgUSJepshPGXebgR
      feuzqc8uiLj5xxH+8yQaGg819f2IiWNmtCIUB88hrsA8/e8u8JAEQwEQaxdYJOBmDr/VZfZONC
      KCvlUr/ejpJXBbckO/oJryCQJMUfmuHIeeaqtMTCSunVoW8PSocPKVEnWx18iy4lSjJOndLw6D
      FPnieRdRKaZ1wwYmlvGSskg0sLQBhg+tn8Km1Mmt7W3AxYbN4NrJSd88jj5C0UxQ==
    OIDC_ISSUER: |-
      AgASAzPwPMbjuudF+csaEY5D+1B+U9yBbs2kUfAeRpjW4D7GRMKrWv9TRNYeBx1gghhjmJ+5ge
      UdH838O9bpC2PGK9ZpM4uE2L1BC4kbFu34zYRln+2uY6mR8wg/1GFzBGeiAC+3GuHjkTrfj92d
      GKIOvIqYwe6GFZ8MMpqZpiAxrMwCyh9UiaH9s4C37vdKOPMokpdl7xJXS3iwpLl4a8reG0YkLb
      1huSyQtMr+VbCNKZoGVr0piOWhvCq287L/kRr3+TQrQUdc/7O8/gpItABYGjT9cXOJfdZYSu6M
      wBtRtA1I0Cna2o08iqn9cWuMrRmKGN2HSHC3RICEVEQCzO6hxM0zuD2PYhZIWuTVDMjeWtyaKe
      MBgMSsdhdJJ8EoIGIqjJZw9Cw1/43MkWEk1UWIumiEC6yCQY1pzx0AmYx/1XJ9TC61Nrp64h+2
      Wb6csAVPKEZdo+cW0V0XL3LOHoD5RABygNF0OI50zwbbuNhe0qk+DvUB8Ojuyxb7uVWFkolC9a
      Ig5Uc3akLJuyWu9O8EajrIicP8DNOBra5qOs3nNA4w0cycFQiaOl2Od9ReePUltHfMdfU38rN0
      388t9CtdBfsRApNl3a+UG2RtggmbqTZKOadtf3aww053RlxmDVBlQ0yhoN7f000tSwx5vygm75
      uPnZRqmFWQTZBleXm1xeT7RzzhUsLhDWerTCNdiFR548eOpxpZ1KBDuPIepV2toIa7dEb2aPFR
      4J9FP9g3KpAHAXoJSwA/aFCVv+vRYkDMK8bZBA==
    OIDC_REDIRECT_URI: |-
      AgBDG8NHyXD3LWfwlmmuQXvJ6b6jaUq4EyyFRGWLiF1Sc3CIoEylCzlrAk6JHcJMUZvqW1GKDg
      KCXNUEl4YDhvNbj6WBcZzfXkUDRLnxo7EmR96AM6OgI0wvtqs3tndCK/zkTK9IYCT2izXneYIX
      WkiFRpp7WgcLKpnjTQGcMW/JVmaIoPVfNMWax4jprUSP6aVQMYH4hHcaA8LAUyKYQhu+rHJgDN
      B6giUks/QAQ3Vq994F291ilXf+8MQdckevJew/GiQlIZ1siyolHTjSkfgBUHV3G3UkgwdM3wKs
      6fZZbL1Fee9JaYu3RJbHSOxvf/HVpFuhJ9suciC6rvwQLvWn++WHzytMYikv3zUl83ypxjQq2R
      0EQhilu4SydLHokn5+icrSOIrFs/x8BOgoOKMt5w50Kv8ZW8BaO5ve0X43mVX1nfDGyRud+tzt
      cigspjN710fvVIHRlPsCj+DBE3qApzsvLTbCdeT7nAsM+PyICLauE56TplzaMY7FN46CLFAkYD
      SDsQlrA+evMI7QLvl3Zm8BsY+zFDaP/Hb075nSgGtDweraDWga8nyFnulztAk/Ro8H55A+AHdV
      nnaUe2Qz0L1P+W5FQWapv7KW6uxursd4qLP1QaTjZrgAHm9G+nPNfXHJUgyoRy0ybenBRm4sTW
      HYXqYSkB/ohhT1IO9qOWUrd7iH5jFoIP8CEEPHNDgOPvoWc6mdRGnJa1tcOKAONrR2Mc7ZIvcK
      LTDuxo2yrF8xuh9WGda/
    SECRET_KEY: |-
      AgBECGKAcqvMOxEHtq0+v8penU98UFVHZtBvRd9cCylfVDqlQ2sy9CKvav/2w5YJtJIRawFnG6
      aJUIYQ/GiO7qsCN23+ml8dao3VGRnbA0CXnCCLr89o6UTzT46xDzYUVDJ8jPh3VS7SeGBjTUup
      4/a6XBPR2KQ5bwBjNY/+jvN8/ocDyOsVnyK9/NIaKOJlthH+IVl1Y77i45NOKgItHm2T3850cl
      jt1eMkRRKd5UWqnjy7avWhVvNmnElt/AHRMv36cEU4oiQM0XVvc8S6z2+2CsA3L0AvR+aFnZVc
      KA5UaTd+txMy1qTnl040yMMQzzlNSoT9dhebCMu1ZDCA0DSytB2H5UREvUclVvPtHXqRPNNlM6
      JXYn/C6xZ5qr39ykGO7V/NradYyrMevXiLEqzSSXH2NBhWIFFp6kvrz4/Ln4bJ3SLLnuGy9NHK
      S6h+LUtMGxl9BUWfugtBnvKjzCzCHvXC3BRUrOpwFnTEHb5IV+flnA9LGnEbPzesxjteSjG0Mx
      toIF3uR0bEjueLeUdFBYW9S60C55+vO6O+K4grIPIZ/t2EMGjHlMAck1oprXvM9R6u0PufmbN6
      8upMdX9aqzba2KwlsQbtj80SFMq9bNZTvXa7lKtFueL8jcPcxK9hgQO5mJqz+7na/KLMd4RYJ+
      XH3sf4grVxC5l9/qewJ7QvkmsYLZ6srAjqG8cbBHdS13AHMsvwq/McBdVbnUt9LqrW3CERhEVy
      SNvvw+Uo6iAXgSpnGerZML4iQPsDEVBIFKwPSruIqnw74DzihhOC
  template:
    metadata:
      name: cost-tracker
      namespace: cost-tracker
