---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: cost-tracker-secrets
  namespace: cost-tracker
spec:
  encryptedData:
    DATABASE_URL: |-
      AgBPSDHuyweRtHU/37a7IBej5DnoYm9wIXIrTvx28HTceL+nqc3/acDBmWIbGAAd+PsCUmKBXu
      Ktk4lIoHgJ9Z2mLoGjNFbrOHFrwDw8SnPFdmxq5w1YVr9G9SNHvVUEqdzNGf0ZChAT4CFGCVOb
      wTYEM6A8SBfV8uDz9nMYohRYahjtKORscOlsD3dkPwldqJ1Pu+K6FvsdIEYOgSmhcbh6EwLyJz
      OdZYxvRegfyL/P/n+BWxAF7c5umxKbHEO9eos3PEgk9LlLFRXsj+jWiNEiEhsn69m9jMJ0mZTk
      2ZUWcJm6pZIiw9jKJkCA9H+y/aq4ro0gk4qvUVB9Fp2T5DaE/mUvV3Elh4RJQ8qPe5J1adJ2IY
      GpKOGPNhQPzjouz0yEEALDyZaNjAhAZNcrsLoJUv/7qRIVoxeQdGfYFh/CN3lmN2PLUPmVhTk4
      b248NqZWRR1oHw4yo6t62PwGBEZBuWWg7eROCecVIEFN1Kp1TFWFsiioIu6HSwNkyYV0QVUGgl
      Kkeg5wyGdfFui0rcotCE1rBbXlboO0it2syZBpKwTmxj8q37czLKn0QboKddruLH27uRhwVHGf
      tE+2Vs8rFMBoWx1opfk1/pix08y9WM8JsDUqDCBg4Xq0zk3UZfq5bUAMaW91+2LBHKmTIZq5bz
      Ce1s8hX/T57EoRfb9daYrTq0CxVKKAcenLN2umDJdWtrfVJb75n5vgaRJQ69yPZmVQweiv7jg+
      c49t1xcp33Bnt4yeNuRzztDF/2wLq7rqsWscnLnEbB2Vz2Kk4RVTplHj+FyK0xxtxSX9elQnEn
      UMfT+ZeYPZJScy923tv8P/HS7dwdS0nOQ6gOpWutiFIs/nJR5Ijj/Q9WjWNN0rZK4=
    GLANCE_API_KEY: |-
      AgAu9+lNIUvvrGlAYSC+GQ25aLomRn1bHwclSlIzksSwYC4YJmppTyIV4U0ijGzq6zmdyXgIlP
      yWlZvjBRAoH2sBzjAO0kKGtuIriy20rdIsZGE5uomKEf1MslZc2f8VIZ93dfRBhBWZZnI+Iaqe
      6vCMWq3yrfAxBemYY/wPGnmT1gZkuEF5emHrkyaBOkEctmhwCVu2Myyr7O7++3AtosnlDU3L9E
      JEkEtnZzu2G9AK3CR39CPL8j7eIAk2z02hA8k5KSmPX6RhLDYM/jMIIS7Fzzgy89SrZ700bmwx
      pcWYj8vxRW+60u7C7rRtq6zmWt3A8Ci62dkxQlfwLDTCUHDQ1sguA/csVKUzyxzWj2dYDUThoi
      47I8BrNM8kmZizMVAzXpjz+zPlXdEBg57bsbwZsnO7uIYLC/WrxvbUYJjlW2+WZ0yjK0f8vnZ6
      t1SFGI3ZA5Yf6ZmFNqtZBWsbKzzz22JVWWoNcvwcuQw9qWFFNhPwQLhkbnwSAYOV4ATnC9e9Zf
      OXm1IerBEHQmyiUSkPIhCho4ujcgxgByH33rSdAfsJxnNnpyni1OBKlxCv2FWu10DI09nuXlbe
      tYvgHwK/DxSSel834cJX2PgIZR5+ZepFpP0k1MYIhMu/3Ni+rX3ujkcc9XFDSwB5Y1BdITzgBM
      AfYY+apTXTj2Jkjhka8zo97kiZ12AsyGmCVkN/F5P2AdR4Ap0Dpqnfwg1vBSM7FCTdb+cgU+E=
    INTERNAL_WEBHOOK_SECRET: |-
      AgAMi4JWUmJwy3HU41nc/V883hzcUvsfMPw0SyetEviPwN+7kC5V5UTPi/9RJ7/LrXesq7co92
      RoLEuE8zIPbKo/7JfB+Ew1OJCawypyT+g7atOqp2qiNYoy2H748ikLZw4UFWoIkbhGTcMupfqI
      GGaZEMecGzq8LA8K4zqMxjYgnlLgoieP9spyDaa/nO7oDvswkPE53Ngi8fpI/D4bylBlTKPkAZ
      kdFTC2SoTtD7AJd61Splw9+Ut3Z2A4nzsfTmsFXYdgyKbZWnKjfe5EVDTcdICweScW96sM5OIF
      WOWN6U4NBaOaIAkj9PzcoZq4VNi0QZ8v4ALWib3+J1KAEhH5fdpMFmE16fqjw6ETZQSYmLESt3
      j6BI9o1mifh1uasPXrGn/BY/Tx5JNsZb3t0Hk7Ji9P8lv5nlXAVMu83BDmHkJFEAkBmtf9+7Q4
      hZfP//RF8lpHqIpb2uPjZprrc1F8uAqKa7jX5Uj0cCdCCfGWeQ2iQzNqcJLmbyS/FubZjTNu5S
      8330BpucDeP1NYavAfoM/5gKwbzKW529BygDVCDhdfD9dWIBoBxxz9uCFa/tuhMOzEJsxL0qTV
      icLbPzznkOWoFYGA42CWkxMlI/bdf5/VdCMYXZ1zLs5OF5WDBNouI7ZEMmSeYaFN6cRRU6huaU
      /UM7ipYSvezI6ePaSUjuooV8ZxflQs5ZWtanMRiQyNIo8W9aCaprMTtecqgUBO4qdNC2fC39g=
    OIDC_CLIENT_ID: |-
      AgA1SQphGMEcC0DElEvLkQWAkBd8Duzxmc9L0u985wVcnsJ80Q2Vm9s4CsJn0MVcg0eqI8OiHz
      BAi8sOW834YrdmbDnTqOoHcbHWgiITcxCon9tTjMn/qVO+bQ9IBSyN3hSgep9qytjJBSS1ctCZ
      DR/uwfha6WuBMWgUkfZ2UmEGh0KR8It8BMczRJQexcJK2drcpdPFPfg3bCsSoMQgri/2cXf0MU
      T1h10iB0MQMaj2MYFNhus3qCLMENcVnm9IStzedE2EU3EMkeBvc/qeMcDuP2K0oSSNRRbQBmSf
      NVJDrdRJpNgJjHFsrI0xvDP3lhGXpr9JMEJe4YcmiAjki8s7caLEhMgPU4dnLsTAEJRPUG8lcO
      X4m2oitmxSVnj7YXdZJKw1FQvHnUd1EiLai22lb++DpIUaJWC+TE9ZGLkSsFw6RcE8h5t88xu9
      ykq3VYLTnkEER2RtzHdDZFBgyKrHTeZqUAYi+qGJC2P3KoHSlzPhea/GX3rp6c0Bu9NVF5qEdC
      eLT7eRfFusjmzktHvDS8AUbo0mreCL8QjDmJtYMogmIJ3Yh/jctWH9p9a8Q6hbE7ty/BdfT4xH
      v5/62ga/I7wSZ/p8VOPpiJ0DuPuqwkJhPIZ6bOuSIapHYOOnXNQKXw9JOB3adRHP8rkzfVdQvq
      cItXoHgHuFp5lnXnkFwEZ3C76t1Bp2ByJ4D2//DCfhEkpukOMBZlrQ+b/sC86kvmFgbqOmRVKf
      qU8jtd3QF43g9xBUzLH3
    OIDC_CLIENT_SECRET: |-
      AgBd7mj3wTtC1+LiTF3kcuIg1+uGqc/pBneEY4ErsOnAprgG+u9grR8FeJ062EHNr4righblR0
      Q/P4TBw1Xw6/QVvai1qcXSFseoykPNvquuqCZlrWDCk0KjQMn0Cli/yDNVmje6qP+7u3jfT+Ji
      xNb1akI5xPI3LuEwMDr8vfrimnJQPDCAbWNmt0Pk1ne+pCgBhQhZ0TerkOCYxcL4xSZFwnOqKm
      jQnX1GhWpQgumnGguBeY1GLlXfzT4eyF0DAwBMz42RKxIv4Pwxtbpab/LVQ/IY5IDVkTcYIfCj
      59Qe+D0W4Tso9ttr9E92l/ObthVREV1GxelN6w9gh938wFThhbg6HiYJXtFoZTrD1wxXPwsX6W
      RUkXd7MLM7foSV/60uWeHHwpmrmbgU8yQBd9hRRCxNPxFT6EQL/AwJ5FvuRmAOl51xI6aUpLVQ
      uoCypxBFEIuR/Ybbp2RFcUCEnyxt+JNgxjziHsQugDBNNL62nJBz5u1RU5VTSg6XORAnf0QIhB
      cWkvHy4nqatGEF0S6MlsBqMMXPAKo3w2157ytWcoYkF+UVsZTBou0xAWMY9m+R1URE4pjGawN1
      l8WPZ4IUGg6dTnWDCzfBMsTJfGHKM6mZlBgatIWj1jN+jbHXKH4AOUXN2MCmx20weRje9+BnxX
      x7kdszVUlxEaqkuMMxbvbYH7vbGXc7Kc7uEZniMO2Bx/elQM+r2CguTKMmiouEemIuKsbCpdyC
      TGSyRyuouIsFrFfA4D/r6izN/qdvqnInZrDVi3h+6nHGvoj3OMTk1Nt8JhYagzjCEo4raNTVtn
      NqctEBA1+6rEQEsFsgYbionnPdDKyR2ZY2323pe8iCtIrNfbwXH5g1FZDY1+F6cw==
    OIDC_ISSUER: |-
      AgDD+l8k8gSNmrENPqmrSmgMl+WmO6ylnrnzfjYU7b7fYh1/n8fp5gfqfCDXVaqkHSKjSNADdA
      xkiAku+sNVRmgcQrTZMjDJ2bHIJ5j7oYQwni9fwkNLCP0t7awVspntnqeCOddJiTadCHoWdfNj
      xWhbOQdQD+kO/EUlxqxdKnky1ft92ZsVuyD0uyGcV5Zjh52j3fPwX00cjkLVA06BkDrxwZFIA+
      uFk/DcLLa6luQkVD/+lTpoiCuG20n0Z3syPWeCgwAmpO3sB9JyLHRkne7thBmgdzEnPIXXJx96
      tRc0mMxRN0F+R/hvRgZf3MwQ02tbPVG8blIp5ELEXiqUI5il5t3UY54/vqQ5R1sHMQ9I+oVIXx
      oX674xsNFUxvNH4ZTByu4GEJj94KJ8yKyntMXVpRS56c5TpB8f93DOT4Aj1KlyPSwhXqHSJJzK
      MurtrQTdARTIKB4VaymGGm20dsvZKn1xCcFNlIUTkSxrt08ZnymrBSLSlgNXY14nEsF7QAKcdi
      BGvbPIBTWjCnTeOFiwZi/nvHu1uNdeZ7sDeYZZg72LjJ6E3l9VwkhbKqifns++MVnLjog3Celi
      eFHmyy+l2tgj8k8XlBSFsAOoq8Zl+m8Fpv0P5mTxTM0uEahwgAi7RsQvDGLXhKLyH8cfoAER6E
      0Se9SfqfknN+ryL/SNyM5HxSAo5EEhMElHPR4LRH09WQCEA4l49/saxepnn7a9fz30HBllYcWm
      StmwxOcP0lM1U/CQEz9jweXIf1LJQMZjJlQPDA==
    OIDC_REDIRECT_URI: |-
      AgCaXVTX88hvf9fVXdTsQuP6n0kgkuxp3bj0WCm/Q1yrciRwADtV6Arh3GQfPNrxhVbfK5VJu9
      BUISe7Oo9Z5JCeK2UcTeSq2G5Mh+PsNAUtbpLJMW4H/irA4RZSgUq7wyaTDDPp2tEXCz1UxOql
      SL8braaw9To+QTiZjEO1KgojAnJ1VL7YxX9M8Ayos0rxEkm9mFiQYuoXUf9NAFlsik9fU9sz5N
      ueFFsbkTCv750MSbKaoi0VFLwghKSfJfj9rX/uDzLJh9b7hnwiE9X4rtDNNQGC02eONGmX1yN0
      SGSkMmQLIsqnz3BRABPpY83kCsqnVKlT92sOXm/PsVl2No3bONDwUgplD+oU33JRfSav1uWbWd
      wWMsym8gtOtSWWUiNgRGBMD4pJO9pzbuP41/PjjWVTOH+HdtYbY7HXFWdPrkCPSZCN/Lakdcsz
      WneQBrpy2m2C9grgVgFS4KF2txY66ClO4X2KsCgOudhMGGCwXyBFTVT8gY5BVQiqZMkXHiTGyF
      AsqSlhk/GZYZpnVXlvrKMH9HMthPmUuQcrDqnQKnqEWP4XhMNm9p23Y6cHO6Skxm2leSjxAT3j
      R38tuQd1cAvpgcrpqpao5q4KWjUKkffWZuwIuzZBBP+24sS5ie1+wWWghA25xYVSY4kUfyvPLB
      nHmVav88pTCcLM3FW+QUViMSXQC9CANzACJD23UWcTEZW77eynjmPVmG9T6W1qeixiODd4KaI7
      rIOoCRW/dQ30vfw9KTSY
    SECRET_KEY: |-
      AgDBgi6KaG+veNPo84ahdDCjsyUy3ty9ZRrXANXG6KVrMFwmq9O/Au3VIZp7SO/vYiFhMn5dGd
      ExLbm7Ngy4wAjWmCzoV9HczODYyly5SD7qDWHT4PQNi3/wGhy+EKVVsLjMmQYrfNX3MbqJeYws
      rWNblPOIz+a66c1UdmKMhUbmhHwhK+6Afd5ccoK4RQHphCV/dAH1n5nZd4yQohDB/wAk4ZCjJ1
      cWyQo8a066NqR7lK636UkQMg66yjYN0/Ktq23yQoxjjlMcU374ZF040bIeaiwxVsVxwuuuY3Il
      tienjXrrJfd6tGHlTjBnA7M91ECaBQ8JC/88UlfNBZ9rUBMecwpqqVK3/GjgWDagjSBVp6ZlFJ
      GXNqI1S5WEYyWOluoL11duuzzqOL2gZjAXgcygfJt2swd3eE9O9qN1JeamDUSfsnlnAUC7a5VK
      HvPuaytEdo3NstBLl8BBJILBJbBTFvdnt2uj8nrzw7xJf2j81X/+WzX/nmz+pVBPeH4oNaazEt
      LN1AokV/nZy4EB0Nis18lOHmgu6HEwiNbpxUNPFzRGJdk/3KXqjrWYPEJacNG8UR/rWJwh2h57
      bFCFWMMerPZA9e6z97a11exrVcw2pTgVOMq41Y8+n0pXcXmH271dpzaoopf45jqDLa1jzdiiCy
      AoJnp5vVh1ysNSz2FpCxX1uS6WIFk8PA6BqHr1P2aFDGioCuHST8jFIqj5aSMK6rAQKpy06f3r
      rlGI5DNlHPTKbidiDlKJeTCn92Z15x1xZKdHec7SmHHkBjQHUeH1
  template:
    metadata:
      name: cost-tracker-secrets
      namespace: cost-tracker
